# Generated by Django 6.0.6 on 2026-06-23 17:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockerAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_resources', to='tenant_module.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocker_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskBlocker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('blocker_type', models.CharField(choices=[('APPROVAL', 'Waiting For Approval'), ('CLIENT', 'Waiting For Client'), ('QA', 'Waiting For QA'), ('DEVOPS', 'Waiting For DevOps'), ('TECHNICAL', 'Technical Blocker')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Blocker'), ('RESOLVED', 'Resolved Blocker')], default='ACTIVE', max_length=15)),
                ('description', models.TextField()),
                ('root_cause', models.CharField(choices=[('REQUIREMENTS_GAP', 'Requirements Gap'), ('DEVOPS_INFRA', 'DevOps / Infrastructure Down'), ('QA_BLOCK', 'QA Verification Blocked'), ('CLIENT_DELAY', 'Waiting for Client Response'), ('CODE_BUG', 'Critical Code Bug'), ('OTHER', 'Other / Unspecified')], default='OTHER', max_length=30)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('sla_hours', models.IntegerField(default=24)),
                ('is_escalated', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_resources', to='tenant_module.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
