# Generated by Django 6.0.6 on 2026-06-23 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planner_module', '0001_initial'),
        ('task_module', '0001_initial'),
        ('tenant_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='task_module.label'),
        ),
        migrations.AddField(
            model_name='task',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_resources', to='tenant_module.organization'),
        ),
        migrations.AddField(
            model_name='task',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='planner_module.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskdependency',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskdependency',
            name='depends_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking_relations', to='planner_module.task'),
        ),
        migrations.AddField(
            model_name='taskdependency',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_resources', to='tenant_module.organization'),
        ),
        migrations.AddField(
            model_name='taskdependency',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_relations', to='planner_module.task'),
        ),
        migrations.AddField(
            model_name='taskdependency',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='dailyplan',
            unique_together={('user', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='taskdependency',
            unique_together={('task', 'depends_on')},
        ),
    ]
