# Generated by Django 6.0.6 on 2026-06-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner_module', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_client_visible',
            field=models.BooleanField(default=False),
        ),
    ]
