# Generated by Django 6.0.6 on 2026-06-23 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner_module', '0003_task_is_client_visible'),
        ('timesheet_module', '0003_project_is_client_visible_clientapprovalrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='timesheet_module.project'),
        ),
    ]
